### PR TITLE
Korean Update Strings

### PR DESCRIPTION
**Pull request by Mangsoi**
I updated the Korean translation. 
(I don't know the functions of Github, please excuse me:))

### CODE REVIEW

**Comment by drakeet** [comment]
Great! Thank you for your help. I will check it soon...

**Comment by drakeet** [comment]
Merged! Thank you very much. I am sending a Pure Writer Pro redeem code for you...

**Comment by drakeet** [comment]
And added you to the Translators list on the about page of Pure Writer. Will publish in v19.95.0

**Comment by Mangsoi** [comment]
> And added you to the Translators list on the about page of Pure Writer. Will publish in v19.95.0

Thank you for merging! But I don't understand your saying-adding me to the translators list?
I'm already in the list, under the name of "망소이".
Did I misunderstand?

**Comment by drakeet** [comment]
Oh, I thought you were someone else, I didn't link you to your GitHub.

**Pull request merged**
